### ISSUE TITLE
DOCS: creating and adding the roadmap to gitpage.

### ISSUE THREAD

**Issue by WillxBernardo** [unb-mds/2024-1-Squad07#2]
## Descrição
Criação de um arquivo de roadmap para acompanhamento detalhado do desenvolvimento do projeto.

## Tarefas

- [x] Criação do documento via plataforma miro
- [x] Adição do arquivo na documentação do projeto (Gitpage)

## Testes / Avaliação
 
- [x] Todos os integrantes possuírem acesso e permissão para editar o roadmap
- [x] O roadmap ser interativo com o usuário da gitpage

## Responsáveis
William Bernardo

## Prazos
03/04/24
